export const products = [
  {
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
];
