export const products = [
  {
    id: 1,
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    id: 2,
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    id: 3,
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    id: 4,
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
  {
    id: 5,
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    id: 6,
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    id: 7,
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    id: 8,
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
  {
    id: 9,
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    id: 10,
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    id: 11,
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    id: 12,
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
  {
    id: 13,
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    id: 14,
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    id: 15,
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    id: 16,
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
  {
    id: 17,
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    id: 18,
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    id: 19,
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    id: 20,
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
  {
    id: 21,
    image: "/gold-jewelry-circle.png",
    title: "خاتم دهب",
    rating: 4.5,
    price: 99.99,
    originalPrice: 129.99,
  },
  {
    id: 22,
    image: "/gold-jewelry-circle.png",
    title: "سلسلة ذهب",
    rating: 4.8,
    price: 199.99,
    originalPrice: 250.0,
  },
  {
    id: 23,
    image: "/gold-jewelry-circle.png",
    title: "أسواره دهب",
    rating: 4.2,
    price: 149.99,
    originalPrice: 179.99,
  },
  {
    id: 24,
    image: "/gold-jewelry-circle.png",
    title: "حلق دهب",
    rating: 4.7,
    price: 89.99,
    originalPrice: 110.0,
  },
];
